### ISSUE TITLE
sitemap.xml question

### ISSUE THREAD

**Issue by amihaiemil** [caarlos0/caarlos0.github.com#69]
@caarlos0 How did you instruct jekyll-sitemap to use the CNAME domain (carlosbecker.com)?

I am using jekyll-sitemap too, but the sitemap.xml is generated with amihaiemil.github.io links instead of amihaiemil.com: http://www.amihaiemil.com/sitemap.xml

**Comment by caarlos0** [comment]
as far as I remember I just created the CNAME file in the root of the site...

**Comment by amihaiemil** [comment]
yeah, I have that too

**Comment by caarlos0** [comment]
have you tried support@github.com?

**Comment by amihaiemil** [comment]
not yet, thanks for the suggestion :)

**Comment by caarlos0** [comment]
np
